title: MusiVerse
description: Serving music for a better

# baseurl: "/doc" # the subpath of your site, e.g. /blog
# url: "http://musiverse.local"      # the base hostname & protocol for your site, e.g. http://example.com

# host: 192.168.42.1
# port: 80

permalink: pretty

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.svg"

# theme
theme: just-the-docs
color_scheme: "dark"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "MusiVerse on GitHub":
      - "https://github.com/Z3NOX/MusiVerse"


exclude: ["tools", "ruby", "node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]
